### ISSUE TITLE
Not working via ssh

### ISSUE THREAD

**Issue by achuthpv** [achuthpv/ldap_printer#5]
I am getting the following error while calling ldap_print from terminal in ubuntu

Initializing Login Sequence...
Loading SSO Login protocol...
Traceback (most recent call last):
  File "/usr/local/ldap_printer/printmain.py", line 34, in <module>
    username, login_status = login()
  File "/usr/local/ldap_printer/oauth/sso_login.py", line 31, in login
    driver = webdriver.Firefox(profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 78, in **init**
    self.binary, timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in **init**
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

**Comment by achuthpv** [comment]
Issue was with the X-server on the remote machine. So invalid and thus closing
